### ISSUE TITLE
关于数据集

### ISSUE THREAD

**Issue by errolyan** [seaniezhao/torch_npss#3]
能不能分享一下，你训练的数据集？

**Comment by seaniezhao** [comment]
用的是作者使用的数据集: NIT-SONG070-F001 (http://hts.sp.nitech.ac.jp/archives/2.3/HTS-demo_NIT-SONG070-F001.tar.bz2).

**Comment by errolyan** [comment]
看来一下你成和的demo，怎么合成的时候又采用了原音频的f0基频？能否留下一个邮箱，我邮箱：2681506@gmail.com,方便沟通。感谢

**Comment by seaniezhao** [comment]
我的邮箱zwxbest@hotmail.com。这里只有原文中的音色模型，f0模型还没实现，所以需要用原音频的f0。生成f0的话可以用一些经典的方法，或者其它模型。原文的f0模型数据要求比较高

**Comment by seaniezhao** [comment]
如果你换了数据集的话，hparam的condition_channel要改成你数据相应的维度
