### ISSUE TITLE
Python package installation errors

### ISSUE THREAD

**Issue by ZacheryGuan** [seaniezhao/torch_npss#4]
I've encountered and solved two errors during installation. I hope the following info would be helpful to others interested in this repo.
1. If you fail to install pyworld during `pip install -r requirement`, use:
 `MACOSX_DEPLOYMENT_TARGET=10.9 pip install pyworld`
instead. See https://github.com/JeremyCCHsu/Python-Wrapper-for-World-Vocoder/issues/1#issuecomment-574017923 for reference.

2. Because of the tensorflow2, the `requirement.txt` can add a tensorflow version descriptor like "1.15.0".

**Comment by dudes17** [comment]
> I've encountered and solved two errors during installation. I hope the following info would be helpful to others interested in this repo.
> 
> 1. If you fail to install pyworld during `pip install -r requirement`, use:
>    `MACOSX_DEPLOYMENT_TARGET=10.9 pip install pyworld`
>    instead. See [JeremyCCHsu/Python-Wrapper-for-World-Vocoder#1 (comment)](https://github.com/JeremyCCHsu/Python-Wrapper-for-World-Vocoder/issues/1#issuecomment-574017923) for reference.
> 2. Because of the tensorflow2, the `requirement.txt` can add a tensorflow version descriptor like "1.15.0".

Thanks, was able to install it finally.

Have you tried to train your own model? Does it work to you?

**Comment by ZacheryGuan** [comment]
I trained the models and the code does work.



---Original---

**Comment by seaniezhao** [comment]
thanks

**Comment by PatrickAi01** [comment]
hello i want to ask if anyone can help, i am running a code  on google collab, i am using m1 mac
i am encountering 

Building wheels for collected packages: pyworld
  error: subprocess-exited-with-error
  
  × Building wheel for pyworld (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for pyworld (pyproject.toml) ... error
  ERROR: Failed building wheel for pyworld
Failed to build pyworld
ERROR: Could not build wheels for pyworld, which is required to install pyproject.toml-based projects


Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu116
Requirement already satisfied: scipy==1.10.1 in /usr/local/lib/python3.10/dist-packages (1.10.1)
Requirement already satisfied: numpy<1.27.0,>=1.19.5 in /usr/local/lib/python3.10/dist-packages (from scipy==1.10.1) (1.23.5)
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu116
Requirement already satisfied: SoundFile==0.12.1 in /usr/local/lib/python3.10/dist-packages (0.12.1)
Requirement already satisfied: cffi>=1.0 in /usr/local/lib/python3.10/dist-packages (from SoundFile==0.12.1) (1.15.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.10/dist-packages (from cffi>=1.0->SoundFile==0.12.1) (2.21)
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu116
Collecting torch==1.13.1
  Downloading https://download.pytorch.org/whl/cu116/torch-1.13.1%2Bcu116-cp310-cp310-linux_x86_64.whl (1977.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 GB 915.7 kB/s eta 0:00:00
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (from torch==1.13.1) (4.7.1)
Installing collected packages: torch
  Attempting uninstall: torch
    Found existing installation: torch 2.0.1+cu118
    Uninstalling torch-2.0.1+cu118:
      Successfully uninstalled torch-2.0.1+cu118
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchaudio 2.0.2+cu118 requires torch==2.0.1, but you have torch 1.13.1+cu116 which is incompatible.
torchdata 0.6.1 requires torch==2.0.1, but you have torch 1.13.1+cu116 which is incompatible.
torchtext 0.15.2 requires torch==2.0.1, but you have torch 1.13.1+cu116 which is incompatible.
torchvision 0.15.2+cu118 requires torch==2.0.1, but you have torch 1.13.1+cu116 which is incompatible.
Successfully installed torch-1.13.1+cu116

does anyone know how to resolve this?

**Comment by seaniezhao** [comment]
it is because of the pyworld package, you could try build it follow https://github.com/JeremyCCHsu/Python-Wrapper-for-World-Vocoder

**Comment by PatrickAi01** [comment]
i will try this out @seaniezhao  
btw may i ask if it is possible to link this via API to my own website?

**Comment by seaniezhao** [comment]
> i will try this out @seaniezhao btw may i ask if it is possible to link this via API to my own website?

Yes, we also have a commercial version available， check this: https://github.com/timedomain-tech/ACE_sequence_file

**Comment by PatrickAi01** [comment]
Hello @seaniezhao thank you for replying, may I ask what the issue is here? something relating to ffmpeg?

<img width="1680" alt="Screenshot 2023-07-25 at 1 28 04 PM" src="https://github.com/seaniezhao/torch_npss/assets/136882606/1259dc5a-12c2-4ede-8d57-736a2e757c43">

**Comment by seaniezhao** [comment]
> Hello @seaniezhao thank you for replying, may I ask what the issue is here? something relating to ffmpeg?
> 
> <img alt="Screenshot 2023-07-25 at 1 28 04 PM" width="1680" src="https://user-images.githubusercontent.com/136882606/255853098-1259dc5a-12c2-4ede-8d57-736a2e757c43.png">

sorry I don't know about this issue
