### ISSUE TITLE
关于测试的标注文件

### ISSUE THREAD

**Issue by Accelerator66** [seaniezhao/torch_npss#5]
请问如何通过wav文件得到.lab标注文件呢？

**Comment by daxiangpanda** [comment]
标注这个东西就是自己标注的
标注有两个文件 一个可以理解为乐谱
另一个可以理解为音素的开始结束时间的标注
我认为.lab文件比wav文件更难整

**Comment by Accelerator66** [comment]
> 标注这个东西就是自己标注的
> 标注有两个文件 一个可以理解为乐谱
> 另一个可以理解为音素的开始结束时间的标注
> 我认为.lab文件比wav文件更难整

我发现有一些align的工具，比如[Montreal-Forced-Aligner](https://montreal-forced-aligner.readthedocs.io/en/latest/introduction.html)，但我并不确定能不能生成相同格式的音素标注

**Comment by daxiangpanda** [comment]
> > 标注这个东西就是自己标注的
> > 标注有两个文件 一个可以理解为乐谱
> > 另一个可以理解为音素的开始结束时间的标注
> > 我认为.lab文件比wav文件更难整
> 
> 我发现有一些align的工具，比如[Montreal-Forced-Aligner](https://montreal-forced-aligner.readthedocs.io/en/latest/introduction.html)，但我并不确定能不能生成相同格式的音素标注

你可以尝试一下  不行可以加我wx一起探讨 17338127681

**Comment by seaniezhao** [comment]
有一些标注工具可以使用，比如praat

**Comment by funkgeek** [comment]
praat生成不了.lab文件，praat论坛有人讨论过这个问题，答案是用叫wavesurfer的软件生成的，官网是https://www.speech.kth.se/wavesurfer/index2.html
（但是我很好奇有没有什么开源项目能直接把textgrid转.lab 如果有人发现麻烦踢我一下哦）

**Comment by seaniezhao** [comment]
> praat生成不了.lab文件，praat论坛有人讨论过这个问题，答案是用叫wavesurfer的软件生成的，官网是https://www.speech.kth.se/wavesurfer/index2.html （但是我很好奇有没有什么开源项目能直接把textgrid转.lab 如果有人发现麻烦踢我一下哦）

不一定必须要.lab文件的，可以看看我另外两个关于npss的仓库，应该是换了textgrid
