### ISSUE TITLE
condition_channel

### ISSUE THREAD

**Issue by telooooo** [seaniezhao/torch_npss#8]
hello!

How do you know what value should be the appropriate dimension of your data? For example, from the given dataset "nitech_jp_song070_f001_029", how to tell its dimension? 

Thank you

**Comment by seaniezhao** [comment]
First you have to know how many kinds if phonemes in this dataset, for example this japanese dataset has 35 different phonemes. And we divide f0 condition to 256 bins, and we will add postion information with 3 dimension. so condition_channel will be 35*3 + 3 + 256

**Comment by telooooo** [comment]
Thank you for answering. I understand how to get the condition_channel value now.

In knowing how many kinds of phonemes in a dataset, does this mean I should re-train it if I intend to use it for a different language since another language may vary in phonemes? Therefore I also need a dataset of that different language?

**Comment by seaniezhao** [comment]
yes, you are right

**Comment by telooooo** [comment]
Thank you for your fast response! :)
